### ISSUE TITLE
Add gather API for model and instance actions

### ISSUE THREAD

**Issue by loppear** [nxus/admin-ui#8]
Args: model identity, action text, url (sub-url?), and options including iconClass:
`app.get('admin-ui').modelAction('user', 'Upload', '/import')`
`app.get('admin-ui').instanceAction('user', 'Resend Invite', '/resendInvite', {iconClass: 'fa-mail'})`

**Comment by alexjreich** [comment]
Sub url, and also should be able to specify a template to render the control.

**Comment by loppear** [comment]
"Download data" is another use, ala Import.
